apiVersion: v1
kind: Secret
metadata:
  name: {{ include "event-service.fullname" . }}-secret
  labels:
  {{- include "event-service.labels" . | nindent 4 }}
data:
  {{- with .Values.database }}
  EVENT_MYSQL_DB_NAME: {{ required "A valid .Values.database.name entry required!" .name | b64enc | quote  }}
  FRONTEGG_EVENTS_MYSQL_DB_HOST: {{ required "A valid .Values.database.host entry required!" .host | b64enc | quote  }}
  FRONTEGG_EVENTS_MYSQL_DB_USERNAME: {{ required "A valid .Values.database.username entry required!" .username | b64enc | quote  }}
  FRONTEGG_EVENTS_MYSQL_DB_PASSWORD: {{ .password | b64enc | quote  }}
  {{- end}}

  {{- with .Values.messageBroker}}
  FRONTEGG_TRIGGER_SLACK_KAFKA_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote  }}
  FRONTEGG_TRIGGER_SLACK_KAFKA_SASL_PASSWORD: {{ .password | b64enc | quote  }}
  FRONTEGG_TRIGGER_WEBHOOK_KAFKA_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote  }}
  FRONTEGG_TRIGGER_WEBHOOK_KAFKA_SASL_PASSWORD: {{ .password | b64enc | quote  }}
  FRONTEGG_TRIGGER_WEBPUSH_KAFKA_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote  }}
  FRONTEGG_TRIGGER_WEBPUSH_KAFKA_SASL_PASSWORD: {{ .password | b64enc | quote  }}
  FRONTEGG_TRIGGER_AUDIT_KAFKA_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote  }}
  FRONTEGG_TRIGGER_AUDIT_KAFKA_SASL_PASSWORD: {{ .password | b64enc | quote  }}
  FRONTEGG_TRIGGER_BELL_KAFKA_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote  }}
  FRONTEGG_TRIGGER_BELL_KAFKA_SASL_PASSWORD: {{ .password | b64enc | quote  }}
  FRONTEGG_TRIGGER_SMS_KAFKA_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote  }}
  FRONTEGG_TRIGGER_SMS_KAFKA_SASL_PASSWORD: {{ .password | b64enc | quote  }}
  FRONTEGG_TRIGGER_EMAIL_KAFKA_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote  }}
  FRONTEGG_TRIGGER_EMAIL_KAFKA_SASL_PASSWORD: {{ .password | b64enc | quote  }}
  FRONTEGG_EVENTS_SERVICE_EVENTS_STATUSES_CONSUMER_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote  }}
  FRONTEGG_EVENTS_SERVICE_EVENTS_STATUSES_CONSUMER_SASL_PASSWORD: {{ .password | b64enc | quote  }}
  {{- end}}

  {{- with .Values.redis}}
  FRONTEGG_EVENTS_SERVICE_REDIS_HOST: {{ required "A valid .Values.redis.host entry required!" .host | b64enc | quote  }}
  FRONTEGG_EVENTS_SERVICE_REDIS_PORT: {{ required "A valid .Values.redis.port entry required!" .port | b64enc | quote  }}
  FRONTEGG_EVENTS_SERVICE_REDIS_PASSWORD: {{ .password | b64enc | quote  }}
  FRONTEGG_EVENTS_SERVICE_REDIS_DB_INDEX: {{ required "A valid .Values.redis.index entry required!" .index | b64enc | quote  }}
  FRONTEGG_EVENTS_SERVICE_REDIS_TLS: {{ required "A valid .Values.redis.tls entry required!" .tls | b64enc | quote  }}
  {{- end}}
