apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webpush-service.fullname" . }}-secret
  labels:
  {{- include "webpush-service.labels" . | nindent 4 }}
data:
  {{- with .Values.database }}
  FRONTEGG_WEBPUSH_MYSQL_DB_HOST: {{ required "A valid .Values.database.host entry required!" .host | b64enc | quote }}
  FRONTEGG_WEBPUSH_MYSQL_DB_USERNAME: {{ required "A valid .Values.database.username entry required!" .username | b64enc | quote }}
  FRONTEGG_WEBPUSH_MYSQL_DB_PASSWORD: {{ .password | b64enc | quote }}
  {{- end }}
  {{- with .Values.messageBroker }}
  FRONTEGG_KAFKA_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote }}
  FRONTEGG_KAFKA_SASL_PASSWORD: {{ .password | b64enc | quote }}
  {{- end }}
  {{- with .Values.frontegg }}
  GOOGLE_ACCOUNT_CLIENT_EMAIL: {{ required "A valid .Values.frontegg.clientEmail entry required!" .clientEmail | b64enc | quote }}
  GOOGLE_ACCOUNT_PRIVATE_KEY: {{ required "A valid .Values.frontegg.googlePrivateKey entry required!" .googlePrivateKey | b64enc | quote }}
  FIREBASE_WEBPUSH_PUBLIC_KEY: {{ required "A valid .Values.frontegg.firebasePublicKey entry required!" .firebasePublicKey | b64enc | quote }}
  FIREBASE_PROJECT_ID: {{ required "A valid .Values.frontegg.firebaseProjectId entry required!" .firebaseProjectId | b64enc | quote }}
  {{- end }}

