# Default values for team-management-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
appVersion: master-latest

image:
  repository: frontegg/team-management-service
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

service:
  type: ClusterIP
  port: 80
  targetPort: 3003
  protocol: TCP
  name: http

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 100m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

nodeSelector:
  "beta.kubernetes.io/os": linux

tolerations: []

affinity: {}

configmap:
  data:
    CLOUD_ENVIRONMENT: dev
    FRONTEGG_SERVICE_NAME: team-management-service
    NODE_ENV: production

secret:
  data: {}

configuration:
  secrets:
    cluster-secret:
      LOGZIO_TOKEN: logzio-token
      FRONTEGG_METADATA_SERVICE_API_KEY: metadata-service-api-key
      FRONTEGG_TEAM_MANAGEMENT_SERVICE_API_KEY: team-management-service-api-key
      FRONTEGG_VENDORS_SERVICE_API_KEY: vendors-service-api-key
      FRONTEGG_TEAM_MANAGEMENT_SERVICE_DB_HOST: team-management-service-db-host
      FRONTEGG_TEAM_MANAGEMENT_SERVICE_DB_USERNAME: team-management-service-db-username
      FRONTEGG_TEAM_MANAGEMENT_SERVICE_DB_PASSWORD: team-management-service-db-password
      FRONTEGG_TEAM_MANAGEMENT_SERVICE_DB_NAME: team-management-service-db-name
      FRONTEGG_TEAM_MANAGEMENT_SERVICE_DB_USE_SSL: team-management-service-db-use-ssl
      FRONTEGG_TEAM_MANAGEMENT_SERVICE_VAULT_URL: team-management-service-vault-url
      AZURE_CLIENT_ID: azure-client-id
      AZURE_CLIENT_SECRET: azure-client-secret
      AZURE_TENANT_ID: azure-tenant-id
      FRONTEGG_ASSET_BLOB_STORAGE_CONNECTION_STRING: asset-blob-storage-connection-string
      FRONTEGG_ASSET_BLOB_STORAGE_CONTAINER_NAME: asset-blob-storage-container-name
      FRONTEGG_TEAM_MANAGEMENT_SERVICE_REDIS_HOST: team-management-service-redis-host
      FRONTEGG_TEAM_MANAGEMENT_SERVICE_REDIS_PORT: team-management-service-redis-port
      FRONTEGG_TEAM_MANAGEMENT_SERVICE_REDIS_PASSWORD: team-management-service-redis-password
      FRONTEGG_TEAM_MANAGEMENT_SERVICE_REDIS_DB_INDEX: team-management-service-redis-db-index
      FRONTEGG_TEAM_MANAGEMENT_SERVICE_REDIS_TLS: team-management-service-redis-tls
      FRONTEGG_ADMINS_SERVICE_API_KEY: admins-service-api-key
      FRONTEGG_IDENTITY_SERVICE_API_KEY: identity-service-api-key

  map:
    cluster-config-map:
      FRONTEGG_METADATA_SERVICE_URL: metadata-service-url
      FRONTEGG_VENDORS_SERVICE_URL: vendors-service-url
      FRONTEGG_IDENTITY_SERVICE_URL: identity-service-url
      FRONTEGG_ADMINS_SERVICE_URL: admins-service-url
