# Default values for webpush-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Provide the amount of pods if HPA is not enabled
replicaCount: 2

# -- Provide the image docker tag default: latest
appVersion: latest

# -- Manage docker image properties
image:
  # -- Provide docker repository hub
  repository: frontegg/hybrid-webpush-service
  # -- Provide image pull policy
  pullPolicy: Always

# -- Provide secret name for frontegg's repository
imagePullSecrets:
  - name: regcred

# -- Provide a name in place of webpush-service for `app:` labels
nameOverride: ""
# -- Provide a name in place of {releaseName}-webpush-service
fullnameOverride: ""

# -- Setup Service properties for webpush-service (open only one port)
service:
  # -- Set service type
  type: ClusterIP
  # -- Set service port
  protocol: TCP
  # -- Set service target port to map
  port: 80
  # -- Set port protocol default: TCP
  targetPort: "3013"
  # -- Set port name
  name: http

# -- HPA properties for webpush-service
# -- If autoscaling is enabled it will monitor the service and raise or lower pods amount based upon usage
# -- If autoscaling is disabled webpush-service will be managed by replicaset with `replicaCount` determine pod amount
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

# -- Set webpush-service resources
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 250m
    memory: 512Mi

nodeSelector:
  "beta.kubernetes.io/os": linux

# -- Provide deployment tolerations
tolerations: []

# -- Provide deployment affinity
affinity: {}

configuration:
  secrets: {}
  map: {}

# -- Set database properties
database:
  # -- Set database host url
  host: ""
  # -- Set database username
  username: ""
  # -- Set database password
  password: ""

# -- Set Message Broker (Kafka) properties.
messageBroker:
  # -- Set broker list (host)
  brokerList: ""
  # -- Set broker list password
  password: ""

frontegg:
  clientEmail: ""
  googlePrivateKey: ""
  firebasePublicKey: ""
  firebaseProjectId: ""
