apiVersion: v1
kind: Secret
metadata:
  name: {{ include "identity-service.fullname" . }}-secret
  labels:
  {{- include "identity-service.labels" . | nindent 4 }}
data:
  {{- with .Values.database }}
  FRONTEGG_IDENTITY_SERVICE_DB_HOST: {{ required "A valid .Values.database.host entry required!" .host }}
  FRONTEGG_IDENTITY_SERVICE_DB_USERNAME: {{ required "A valid .Values.database.username entry required!" .username }}
  FRONTEGG_IDENTITY_SERVICE_DB_PASSWORD: {{ required "A valid .Values.database.password entry required!" .password }}
  FRONTEGG_IDENTITY_SERVICE_DB_USE_SSL: {{ required "A valid .Values.database entry.ssl required!" .ssl }}
  {{- end }}
  {{- with .Values.redis }}
  FRONTEGG_IDENTITY_SERVICE_REDIS_HOST: {{ required "A valid .Values.redis.host entry required!" .host }}
  FRONTEGG_IDENTITY_SERVICE_REDIS_PASSWORD: {{ required "A valid .Values.redis.password entry required!" .password }}
  FRONTEGG_IDENTITY_SERVICE_REDIS_PORT: {{ required "A valid .Values.redis.port entry required!" .port }}
  FRONTEGG_IDENTITY_SERVICE_REDIS_TLS: {{ required "A valid .Values.redis.tls entry required!" .tls }}
  {{- end }}
  FRONTEGG_SENDGRID_API_KEY: {{ required "A valid .Values.email.apiKey entry required!" .Values.email.apiKey }}
