kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "team-management-service.fullname" . }}-configmap
  labels:
  {{- include "team-management-service.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap.data | nindent 4 }}
