kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "team-management-service.fullname" . }}-configmap
  labels:
  {{- include "team-management-service.labels" . | nindent 4 }}
data:
  CLOUD_ENVIRONMENT: prod
  FRONTEGG_SERVICE_NAME: team-management-service
  NODE_ENV: production
  {{- with .Values.network }}
  FRONTEGG_METADATA_SERVICE_URL: {{ required "A valid .Values.network.metadataServiceUrl entry required!" .metadataServiceUrl}}
  FRONTEGG_VENDORS_SERVICE_URL: {{ required "A valid .Values.network.vendorsServiceUrl entry required!" .vendorsServiceUrl}}
  FRONTEGG_IDENTITY_SERVICE_URL: {{ required "A valid .Values.network.identityServiceUrl entry required!" .identityServiceUrl}}
  FRONTEGG_ADMINS_SERVICE_URL: {{ required "A valid .Values.network.adminsServiceUrl entry required!" .adminsServiceUrl}}
  {{- end}}
  FRONTEGG_HYBRID_MODE: "true"
  FRONTEGG_ADMINS_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_VENDORS_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_METADATA_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_IDENTITY_SERVICE_API_KEY:  "frontegg-api-key"
  FRONTEGG_TEAM_MANAGEMENT_SERVICE_API_KEY: "frontegg-api-key"
