apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-management-service.fullname" . }}-secret
  labels:
  {{- include "team-management-service.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secret.data | nindent 2 }}
