apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-management-service.fullname" . }}-secret
  labels:
  {{- include "team-management-service.labels" . | nindent 4 }}
data:
  {{- with .Values.database }}
  FRONTEGG_TEAM_MANAGEMENT_SERVICE_DB_HOST: {{ required "A valid .Values.database.host entry required!" .host | b64enc | quote }}
  FRONTEGG_TEAM_MANAGEMENT_SERVICE_DB_USERNAME: {{ required "A valid .Values.database.userName entry required!" .userName | b64enc | quote }}
  FRONTEGG_TEAM_MANAGEMENT_SERVICE_DB_PASSWORD: {{ required "A valid .Values.database.password required!" .password | b64enc | quote }}
  FRONTEGG_TEAM_MANAGEMENT_SERVICE_DB_NAME: {{ required "A valid .Values.database.name entry required!" .name | b64enc | quote }}
  FRONTEGG_TEAM_MANAGEMENT_SERVICE_DB_USE_SSL: {{ required "A valid .Values.database.ssl entry required!" .ssl | b64enc | quote }}
  {{- end }}
  {{- with .Values.redis }}
  FRONTEGG_TEAM_MANAGEMENT_SERVICE_REDIS_HOST: {{ required "A valid .Values.redis.host entry required!" .host | b64enc | quote }}
  FRONTEGG_TEAM_MANAGEMENT_SERVICE_REDIS_PORT: {{ required "A valid .Values.redis.port entry required!" .port | b64enc | quote }}
  FRONTEGG_TEAM_MANAGEMENT_SERVICE_REDIS_PASSWORD: {{ required "A valid .Values.redis.password entry required!" .password | b64enc | quote }}
  FRONTEGG_TEAM_MANAGEMENT_SERVICE_REDIS_DB_INDEX: {{ required "A valid .Values.redis.index entry required!" .index | b64enc | quote }}
  FRONTEGG_TEAM_MANAGEMENT_SERVICE_REDIS_TLS: {{ required "A valid .Values.redis.tls entry required!" .tls | b64enc | quote }}
  {{- end }}
  {{- with .Values.saml }}
  FRONTEGG_SAML_PRIVATE_KEY: {{ required "A valid .Values.saml.privateKey entry required!" .privateKey | b64enc | quote }}
  FRONTEGG_SAML_PUBLIC_KEY: {{ required "A valid .Values.saml.publicKey entry required!" .publicKey | b64enc | quote }}
  FRONTEGG_SAML_CERTIFICATE: {{ required "A valid .Values.saml.certificate entry required!" .certificate | b64enc | quote }}
  {{- end }}
  {{- with .Values.frontegg }}
  CLIENT_ID: {{ required "A valid .Values.frontegg.clientId entry required!" .clientId | b64enc | quote }}
  {{- end }}
