apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connectors-worker.fullname" . }}-secret
  labels:
  {{- include "connectors-worker.labels" . | nindent 4 }}
data:

  FRONTEGG_INTEGRATIONS_SERVICE_API_KEY: "frontegg-api-key"

  {{- with .Values.messageBroker }}
  FRONTEGG_KAFKA_SLACK_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote }}
  FRONTEGG_KAFKA_SLACK_SASL_PASSWORD: {{ required "A valid .Values.messageBroker.password entry required!" .password | b64enc | quote }}
  FRONTEGG_KAFKA_EMAIL_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote }}
  FRONTEGG_KAFKA_EMAIL_SASL_PASSWORD: {{ required "A valid .Values.messageBroker.password entry required!" .password | b64enc | quote }}
  FRONTEGG_KAFKA_SMS_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote  }}
  FRONTEGG_KAFKA_SMS_SASL_PASSWORD: {{ required "A valid .Values.messageBroker.password entry required!" .password | b64enc | quote }}
  FRONTEGG_KAFKA_EVENTS_STATUS_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote }}
  FRONTEGG_KAFKA_EVENTS_STATUS_SASL_PASSWORD: {{ required "A valid .Values.messageBroker.password entry required!" .password | b64enc | quote }}
  {{- end }}
  {{- with .Values.redis }}
  FRONTEGG_CONNECTORS_WORKER_SERVICE_REDIS_HOST: {{ required "A valid .Values.redis.host entry required!" .host | b64enc | quote }}
  FRONTEGG_CONNECTORS_WORKER_SERVICE_REDIS_PORT: {{ required "A valid .Values.redis.port entry required!" .port | b64enc | quote }}
  FRONTEGG_CONNECTORS_WORKER_SERVICE_REDIS_DB_INDEX: {{ required "A valid .Values.redis.index entry required!" .index | b64enc | quote }}
  FRONTEGG_CONNECTORS_WORKER_SERVICE_REDIS_TLS: {{ required "A valid .Values.redis.tls entry required!" .tls | b64enc | quote }}
  FRONTEGG_CONNECTORS_WORKER_SERVICE_REDIS_PASSWORD: {{ required "A valid .Values.redis.password entry required!" .password | b64enc | quote }}
  {{- end }}
  {{- with .Values.frontegg }}
  FRONTEGG_SENDGRID_API_KEY: {{ required "A valid .Values.frontegg.emailKey entry required!" .emailKey | b64enc | quote }}
  {{- with .twilio }}
  FRONTEGG_TWILIO_SENDER: {{ required "A valid .Values.frontegg.twilio.sender entry required!" .sender | b64enc | quote }}
  FRONTEGG_TWILIO_TOKEN: {{ required "A valid .Values.frontegg.twilio.token entry required!" .token | b64enc | quote }}
  FRONTEGG_TWILIO_ACCOUNTSID: {{ required "A valid .Values.frontegg.twilio.accoundId entry required!" .accountId | b64enc | quote }}
  {{- end }}
  {{- end }}
