replicaCount: 2

autoscaling:
  enabled: true

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 250m
    memory: 512Mi

configmap:
  data:
    CLOUD_ENVIRONMENT: prod
    NODE_ENV: production
