kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "notification-service.fullname" . }}-configmap
  labels:
  {{- include "notification-service.labels" . | nindent 4 }}
data:
  CLOUD_ENVIRONMENT: prod
  NODE_ENV: production
  FRONTEGG_VENDORS_SERVICE_URL: http://frontegg-notification-service
  FRONTEGG_NOTIFICATION_SERVICE_API_KEY: "frontegg-api-key"
  FRONTEGG_VENDORS_SERVICE_API_KEY: "frontegg-api-key"