apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-service.fullname" . }}-secret
  labels:
  {{- include "notification-service.labels" . | nindent 4 }}
data:
  FRONTEGG_MONGODB_URL: {{ required "A valid .Values.mongodb.url entry required!" .Values.mongodb.url | b64enc | quote }}
  {{- with .Values.database }}
  FRONTEGG_NOTIFICATIONS_MYSQL_DB_HOST: {{ required "A valid .Values.database.host entry required!" .host | b64enc | quote }}
  FRONTEGG_NOTIFICATIONS_MYSQL_DB_PASSWORD: {{ .password | b64enc | quote }}
  FRONTEGG_NOTIFICATIONS_MYSQL_DB_USERNAME: {{ required "A valid .Values.database.username entry required!" .username | b64enc | quote }}
  {{- end }}
  {{- with .Values.messageBroker }}
  FRONTEGG_KAFKA_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote }}
  FRONTEGG_KAFKA_SASL_PASSWORD: {{ .password | b64enc | quote }}
  {{- end}}
