apiVersion: v2
name: connectivity
description: Frontegg's Connectivity Helm chart for Kubernetes
type: application
version: 0.1.0-beta16

dependencies:
  - name: connectors-worker
    version: "0.1.*"
    repository: "https://frontegg.github.io/helm-charts/"
  - name: event-service
    version: "0.1.*"
    repository: "https://frontegg.github.io/helm-charts/"
  - name: integrations-service
    version: "0.1.*"
    repository: "https://frontegg.github.io/helm-charts/"
  - name: notification-service
    version: "0.1.*"
    repository: "https://frontegg.github.io/helm-charts/"
  - name: webpush-service
    version: "0.3.*"
    repository: "https://frontegg.github.io/helm-charts/"

maintainers:
  - name: "Guy Ludvig"
    email: "guy@frontegg.com"
